name: Update Gradle Wrapper

on:
  push:
    branches:
      - temp

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  discussions: write
  id-token: write
  issues: none
  packages: none
  pages: none
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v2
